ttsx/shopping/urls.py
#coding=utf-8
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.index, name='index'),#首页
    url(r'^list/(\w+)/(\w+)/(\d*)$', views.list, name='list'),#列表页
    url(r'^search/(\w+)/(\d+)$', views.search, name='search'),#搜索页
    url(r'^detail/(\w+)/(\d+)$', views.detail, name='detail'),#详情页
    url(r'^addgoods/$', views.addgoods, name='addgoods'),
    url(r'^order/$', views.buy_now, name='order'),#立即购买
    url(r'^notpaid/$', views.notpaid, name='notpaid'),
]

ttsx/ttsx/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('shopping.urls', namespace='shopping')),
    url(r'^userCenter/', include('userCenter.urls', namespace='userCenter')),
    url(r'^favicon.ico$', RedirectView.as_view(url=r'static/favicon.ico')),
]+ static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

ttsx/userCenter/urls.py
#coding=utf-8
from django.conf.urls import url
from userCenter import views
urlpatterns = [
    url(r'^cart/$',views.cart, name='cart'),
    url(r'^cartdel$', views.cartdel, name='cartdel'),
    url(r'^cartchange$', views.cartchange, name='cartchange'),
    url(r'^isselect$', views.isselect, name='isselect'),
    url(r'^allselect$', views.allselect, name='allselect'),
    url(r'^login/$', views.login_register_split, {'get': views.login, 'post': views.toLogin}, name='login'),
    url(r'^logout/$', views.logout_view),
    url(r'^register/$', views.login_register_split, {'get': views.register, 'post': views.createUser}, name='register'),
    url(r'^userCenterInfo/$', views.userCenterInfo),
    url(r'^userCenterSite/$', views.userCenterSite),
    url(r'^userCenterOrder([0-9]*)/$', views.userCenterOrder),
    url(r'^userCenterSite/userAddressUpdate$', views.updatehandler),
]

ttsx/userCenter/models.py
#coding=utf-8
from shopping.models import *
from django.contrib.auth.models import User


class cart(models.Model):
    num = models.IntegerField(verbose_name='数量')
    user = models.ForeignKey(User)
    goods_info = models.ForeignKey(GoodsInfo)
    isselect = models.BooleanField()
    class Meta:
        db_table = 'cart'
        verbose_name = '购物车'
        verbose_name_plural = verbose_name
class address_info(models.Model):
    receiver = models.CharField(max_length=15,verbose_name='收件人')
    tel = models.CharField(max_length=15,verbose_name='电话号码')
    email = models.EmailField(verbose_name='邮箱')
    zipcode = models.CharField(max_length=10,verbose_name='邮编')
    address = models.CharField(max_length=50,verbose_name='地址')
    user = models.ForeignKey(User)
    isDelete = models.BooleanField(default=0)
    class Meta:
        verbose_name = '地址信息'
        verbose_name_plural = verbose_name
        db_table = 'address_info'
    # 后台admin站点添加数据显示名字而不是对象
    def __str__(self):
        # __unicode__
        return self.user.username.encode('utf-8')

class OrderInfo(models.Model):
    user = models.ForeignKey(User)
    state = models.BooleanField(verbose_name='支付状态')
    total = models.DecimalField(max_digits=5,decimal_places=2,verbose_name='支付金额')
    ordernum = models.CharField(max_length=30,verbose_name='订单号')
    bpub_date = models.DateTimeField(verbose_name='订单日期',auto_now_add=True)
    class Meta:
        verbose_name = '订单'
        verbose_name_plural = verbose_name
        db_table = 'OrderInfo'
    def __str__(self):
        return str(self.total)

class OrderDetailInfo(models.Model):
    order = models.ForeignKey(OrderInfo)
    goods = models.ForeignKey(GoodsInfo)
    goods_price = models.DecimalField(max_digits=5,decimal_places=2,verbose_name='商品价格')
    count = models.IntegerField(verbose_name='商品数量')
    class Meta:
        verbose_name = '订单详情'
        verbose_name_plural = verbose_name
        db_table = 'OrderDetailInfo'

ttsx/userCenter/views.py
#coding=utf-8
import userCenter
from django.shortcuts import redirect
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django import forms
from django.contrib import auth

from shopping.views import *
def login_register_split(request,get,post):
    if request.method == 'GET':
        return get(request)
    elif request.method == 'POST':
        return post(request)
    else:
        raise Http404
#注册页面

def register(request):
    return render(request,'userCenter/register.html')

@login_required()
def cart(request):
    userId = request.user.id
    userCenter.models.cart.objects.filter(user_id=userId).update(isselect=1)
    cartAll = userCenter.models.cart.objects.filter(user_id=userId)
    if cartAll.exists():
        noGoods=0
    else:
        noGoods=1
    context = {'cartAll':cartAll,'noGoods':noGoods}
    return render(request,'userCenter/cart.html', context)


def cartdel(request):
    cart_good_id = request.GET.get('cart_good_id')
    userCenter.models.cart.objects.get(pk = cart_good_id).delete()
    return HttpResponse('ok')


def cartchange(request):
    num = request.GET.get('num')
    cart_good_id = request.GET.get('cart_good_id')
    good = userCenter.models.cart.objects.get(pk=cart_good_id)
    good.num = num
    good.save()
    return HttpResponse('ok')


def isselect(request):
    goodsid = request.GET.get('goodsid')
    val = request.GET.get('val')
    good = userCenter.models.cart.objects.get(pk=goodsid)
    good.isselect = int(val)
    good.save()
    return HttpResponse('ok')


def allselect(request):
    val = request.GET.get('val')
    userCenter.models.cart.objects.all().update(isselect=int(val))
    return HttpResponse('ok')


#验证提交信息的正确性
class ttsxUser(forms.Form):
    name = forms.CharField(max_length=20,min_length=3)
    pwd = forms.CharField(max_length=20,min_length=6)
    email = forms.EmailField(max_length=30,min_length=3)
#注册用户
def createUser(request):
    form = ttsxUser(request.POST)
    isCreate = False
    if form.is_valid():
        info = form.cleaned_data
        try:
            #用户名已经存在抛异常
            user = User.objects.create_user(username=info['name'],password=info['pwd'],email=info['email'])
            user.save()
            #用户注册后自登陆
            user = auth.authenticate(username=info['name'], password=info['pwd'])
            auth.login(request, user)
        except Exception,e:
            pass
        else:
            isCreate = True

    return JsonResponse({'register':isCreate})


#登陆页面
def login(request):
    # print request.META['HTTP_REFERER']
    return  render(request,'userCenter/login.html')

#用户登陆
from django.contrib.auth.models import User
def toLogin(request):
    come = request.GET.get('next',None)
    username = request.POST.get('username', '')
    pwd = request.POST.get('pwd', '')
    user = auth.authenticate(username=username, password=pwd)
    isLogin = False
    if user is not None and user.is_active:
        auth.login(request,user)
        isLogin = True
    return  JsonResponse({'login':isLogin,'come':come})
#退出登陆
def logout_view(request):
    auth.logout(request)
# 可以根据需求跳转到特定页面
    return HttpResponseRedirect("/")
#用户信息
@login_required()
def userCenterInfo(request):
    #判断用户是否登陆
    userId = request.user.id
    puser = User.objects.get(pk=userId)
    addr = address_info.objects.filter(user=puser.pk)
    if not addr:
        addr = ['']
    recents = []
    if request.session.get('recent_goods'):
        recent_goods = request.session.get('recent_goods')
        for recent_good in recent_goods:
            recent = GoodsInfo.objects.get(id=recent_good)
            recents.append(recent)
    context = {'user':puser,'addr':addr[0], 'recents':recents[::-1]}
    return  render(request,'userCenter/user_center_info.html',context)

#用户地址
def userCenterSite(request):
    userId = request.user.id
    puser = User.objects.get(pk=userId)
    addr = address_info.objects.filter(user=puser.pk)
    if not addr:
        addr=['']
    context = {'user': puser, 'addr': addr[0]}
    return render(request,'userCenter/user_center_site.html',context)


#用户全部订单

@login_required()
def userCenterOrder(request,pIndex):
    userId=request.user.id
    #根据登陆用户id查处他的订单
    if request.GET.get('orderid'):
        orderid = request.GET.get('orderid')
        OrderInfo.objects.filter(id=orderid).update(state=1)
    orders = OrderInfo.objects.filter(user=userId)[::-1]
    #分页
    pgi = Paginator(orders,3)
    if pIndex =='':
        pIndex='1'
    orders2 = pgi.page(int(pIndex))
    pagelist = pgi.page_range
    context = {'orders':orders2,'pagelist':pagelist,'pIndex':pIndex}
    return  render(request,'userCenter/user_center_order.html',context)

#修改地址数据
def updatehandler(request):
    userId = request.user.id
    uname = request.POST['uname']
    uaddress = request.POST['address']
    uzipcode = request.POST['zipcode']
    utelp = request.POST['tel']
    # context = {'uname':uname,'address':address,'zipcode':zipcode,'tel':tel}
    #存储数据到数据库
    try :
        temp=address_info.objects.filter(id=userId)[0]
    except:
        temp = address_info()
    temp.receiver=uname
    temp.address=uaddress
    temp.tel=utelp
    temp.zipcode=uzipcode
    temp.user=request.user
    temp.save()
    return redirect('/userCenter/userCenterSite/')

ttsx/userCenter/templates/userCenter/cart.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
天天生鲜-购物车
{% endblock %}


{% block head %}
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<link rel="stylesheet" type="text/css" href="{%static 'css/reset.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/main.css'%}">
    <script type="text/javascript", src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
    $(function () {
        $(".settlements .col04 a").click(function (event) {
            var flag1={{ noGoods }};
            if(flag1){
            alert ('亲，选点宝贝再结账吧')
            event.preventDefault();
            }
            else{
                flag2 = true
                $(".cart_list_td .col01 input").each(function() {
                    if($(this).is(':checked')){
                        flag2 = false
                        return false
                    }
                    else{
                        flag2 = true
                    }
                })
                if(flag2){
                    alert ('亲，选点宝贝再结账吧')
                    event.preventDefault();
                }
            }
        })
        {#页面加载完成后进行初始化，包括小计，商品数，总价，总计商品数#}
        $(".cart_list_td").each(function () {
            $(this).children(".col05")
            price = parseFloat($(this).children(".col05").text())
            num = $(this).find(".num_show").val()
            subtotal = (num*price).toFixed(2)+'元'
            $(this).children(".col07").text(subtotal)
        })
        goodsnum()
        total()
        {#当+按下后，调用函数，改变数量、小计、总计#}
        $(".add").click(function () {
            var obj = $(this)
            add1(obj)
            total()
        })
        {#当-按下后，调用函数，改变数量、小计、总计#}
        $(".minus").click(function () {
            var obj = $(this)
            sub1(obj)
            total()
        })
        {#当删除操作时，将此商品删除,并从数据库中删除#}
        $(".col08").click(function () {
            $(this).parent().remove()
            goodsnum()
            total()
            cart_good_id = $(this).siblings("#cart_good_id").text()
            $.get("{% url 'userCenter:cartdel' %}", {'cart_good_id':cart_good_id})
        })
        {#当商品复选框发生变化时，计算总价，改变全选复选框的状态#}
        $(".cart_list_td .col01 input").change(function () {
            goodsid = $(this).parent().siblings("#cart_good_id").text()
            if($(this).is(':checked')){
                $.get("{% url 'userCenter:isselect' %}",{'goodsid':goodsid, 'val':1})
            }
            else{
                $.get("{% url 'userCenter:isselect' %}",{'goodsid':goodsid, 'val':0})
            }
           total()
           var Flag = true
           $(".cart_list_td .col01 input").each(function() {
                if($(this).is(':checked')){
                    Flag = true
                }
                else{
                    Flag = false
                    $(".settlements .col01 input").prop("checked",false)
                    return false
                }
            })
            if(Flag){
                $(".settlements .col01 input").prop("checked",true)
            }
        })
        {#当全选复选框发生变化时，改变商品复选框状态#}
        $(".settlements .col01 input").change(function () {
            if($(this).is(':checked')){
                $.get("{% url 'userCenter:allselect' %}",{'val':1})
                $(".cart_list_td .col01 input").each(function() {
                    $(this).prop("checked",true)
                })
            }
            else{
                $.get("{% url 'userCenter:allselect' %}",{'val':0})
                $(".cart_list_td .col01 input").each(function() {
                    $(this).prop("checked",false)
                })
            }
            total()
        });
        {#当input框数字变化时#}
        $(".num_add .num_show").bind('input propertychange', function() {
            price = parseFloat($(this).parents("ul").children(".col05").text())
            num = parseInt($(this).val())
            if(isNaN(num)){
                num=0
            }
            subtotal = (num * price).toFixed(2) + '元'
            $(this).parents("ul").children(".col07").text(subtotal)
            cart_good_id = $(this).parents("ul").children("#cart_good_id").text()
            $.get("{% url 'userCenter:cartchange' %}",{'num':num, 'cart_good_id':cart_good_id})
            total()
        })

    });
    {#定义添加函数，当按下+时，数量显示值+1，同时，计算小计并更新数据库的商品数.click事件发生时，调用此函数.#}
    function add1(obj) {
        num = obj.siblings(".num_show").val()
        obj.siblings(".num_show").val(num*1+1)
        price = parseFloat(obj.parents("ul").children(".col05").text())
        num = obj.siblings(".num_show").val()
        subtotal = (num*price).toFixed(2)+'元'
        obj.parents("ul").children(".col07").text(subtotal)
        cart_good_id = obj.parents("ul").children("#cart_good_id").text()
        $.get("{% url 'userCenter:cartchange' %}",{'num':num, 'cart_good_id':cart_good_id})
    };
    {#定义减少函数，当按下-时，数量显示值-1并跟新数据库的商品数。当值为1时不再减  #}
    function sub1(obj) {
        num = parseFloat(obj.siblings(".num_show").val())
            if (num>1) {
                obj.siblings(".num_show").val(num - 1)
                price = parseFloat(obj.parents("ul").children(".col05").text())
                num = obj.siblings(".num_show").val()
                subtotal = (num * price).toFixed(2) + '元'
                obj.parents("ul").children(".col07").text(subtotal)
                cart_good_id = obj.parents("ul").children("#cart_good_id").text()
                $.get("{% url 'userCenter:cartchange' %}",{'num':num, 'cart_good_id':cart_good_id})
                }
    };
    {#定义计算总价及总计函数，首先判断复选框是否选中，当复选框选中时纳入计算。遍历所有商品复选框，当选中时，分别计算将价格和数量相加#}
    function total() {
        var total = 0.0
        var num = 0.0
        $(".cart_list_td .col01 input").each(function () {
            if($(this).is(':checked')){
                total = total+parseFloat($(this).parents("ul").children(".col07").text())
                num1 = parseFloat($(this).parents("ul").find(".num_show").val())
                 if(isNaN(num1)){
                    num1=0
                 }
                num = num+num1
            }
        })
        $(".settlements .col03 em").text(total.toFixed(2))
        $(".settlements .col03 b").text(num)
    };
    {#计算商品总类数#}
    function goodsnum() {
        var num = 0
        $(".cart_list_td").each(function () {
            num = num+1
        })
        $(".total_count em").text(num)
    }
    </script>
{% endblock %}


{% block content %}
<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="{% static 'images/logo.png'%}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<form action="{% url 'shopping:search' 'id' 1%}" method="get">
			<input type="text" class="input_text fl" name="search_good" id="search_text" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" id="search_button" value="搜索">
            <p><span id='search_result'></span></p>
            </form>
		</div>
	</div>

	<div class="total_count">全部商品<em></em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    {% for cart_good in cartAll %}
	<ul class="cart_list_td clearfix">
        <li hidden id="cart_good_id">{{ cart_good.id }}</li>
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="{{ cart_good.goods_info.smallImg }}"></li>
		<li class="col03">{{ cart_good.goods_info.info }}<br><em>{{ cart_good.goods_info.price }}元/{{ cart_good.goods_info.unit }}</em></li>
		<li class="col04">{{ cart_good.goods_info.unit }}</li>
		<li class="col05">{{ cart_good.goods_info.price }}</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="{{ cart_good.num }}">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07" id="subtotal">{{ cart_good.goods_info.price }}</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
    {% endfor %}



	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em></em><br>共计<b></b>件商品</li>
		<li class="col04"><a href="{% url 'shopping:order' %}">去结算</a></li>
	</ul>
{% endblock %}

ttsx/userCenter/templates/userCenter/login.html
{% load staticfiles %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/login.js' %}"></script>
</head>
<body>
	<div class="login_top clearfix">
		<a href="{% url 'shopping:index' %}" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'userCenter:register' %}">立即注册</a>
				</div>

				<div class="form_input">
					<div class="user_error">用户名或者密码错误</div>
					<form action="">
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

ttsx/userCenter/templates/userCenter/user_center_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript", src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $(".add_goods").click(function () {
                goodsid = $(this).parent().siblings("#goodsid").text()
				goodsnum = 1
                $.post("{% url 'shopping:addgoods' %}",{'goodsid':goodsid, 'goodsnum':goodsnum},function(dic){
				})
            })
        })
    </script>
{% endblock head %}

{% block content %}
	<div class="search_bar clearfix">
		<a href="{% url 'shopping:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fl">
			<form action="{% url 'shopping:search' 'id' 1%}" method="get">
			<input type="text" class="input_text fl" name="search_good" id="search_text" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" id="search_button" value="搜索">
            <p><span id='search_result'></span></p>
            </form>
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/userCenter/userCenterInfo/" class="active">· 个人信息</a></li>
				<li><a href="/userCenter/userCenterOrder/">· 全部订单</a></li>
				<li><a href="/userCenter/userCenterSite/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{user.username}}</li>
							<li><span>联系方式：</span>{{ addr.tel}}</li>
							<li><span>联系地址：</span>{{ addr.address }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for temp in recents %}
                        <li>
                            <a href="{% url 'shopping:detail' temp.type temp.id %}"><img src="{{temp.smallImg}}"></a>
                            <h4><a href="{% url 'shopping:detail' temp.type temp.id %}">{{ temp.info }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ temp.price }}</span>
                                <span class="unit">{{ temp.price }}/{{ temp.unit }}</span>
                                <a href="javascript:;" class="add_goods" title="加入购物车"></a>
                            </div>
                            <p id="goodsid" hidden>{{ temp.id }}</p>
                        </li>
                        {% endfor %}
			</ul>
		</div>
		</div>
	</div>



{% endblock content %}
</body>
</html>

ttsx/userCenter/templates/userCenter/user_center_order.html
{% extends 'base.html' %}
{% block title %}天天生鲜-用户中心{% endblock title%}
{% block head %}
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script src="/static/jss/jquery-1.12.4.min.js"></script>
{% endblock head %}

{% block  content %}

	<div class="search_bar clearfix">
		<a href="{% url 'shopping:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;用户中心</div>
		<div class="search_con fl">
            <form action="{% url 'shopping:search' 'id' 1%}" method="get">
			<input type="text" class="input_text fl" name="search_good" id="search_text" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" id="search_button" value="搜索">
            <p><span id='search_result'></span></p>
            </form>
		</div>
	</div>


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/userCenter/userCenterInfo/">· 个人信息</a></li>
				<li><a href="/userCenter/userCenterOrder/" class="active">· 全部订单</a></li>
				<li><a href="/userCenter/userCenterSite/">· 收货地址</a></li>
			</ul>
		</div>

		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for temp in orders %}
                    <ul class="order_list_th w978 clearfix">
                        <li class="col01">{{ temp.bpub_date }}</li>
                        <li class="col02">订单号：{{ temp.ordernum  }}</li>
                    {% if temp.state == 1 %}
                        <li class="col02 stress">支付</li>
                    {% elif temp.state == 0 %}
                        <li class="col02 stress"style="color: #c40000">未支付</li>
                    {% endif %}
                    </ul>

                    <table class="order_list_table w980">
                        <tbody>
                            <tr>
                                <td width="55%">
                                    {% for temp1 in temp.orderdetailinfo_set.all %}
                                    <ul class="order_goods_list clearfix">
                                        <li class="col01"><img src="{{ temp1.goods.smallImg.url }}"></li>
                                        <li class="col02"><em>{{ temp1.goods.title }}</em></li>
                                        <li class="col03">{{temp1.count}}</li>
                                        <li class="col04">{{ temp1.goods_price}}</li>
                                    </ul>
                                    {% endfor %}
                                </td>
                                        <td width="15%">{{ temp.total }}元</td>
                                    {%  if temp.state == 1%}
                                        <td width="15%" >已付款</td>
                                        <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                                    {% elif temp.state == 0%}
                                        <td width="15%">未付款</td>
                                        <td width="15%"><a href="{% url 'shopping:notpaid' %}?ordernum={{ temp.ordernum }}" class="oper_btn">去付款</a></td>
                                    {% endif %}
                            </tr>
                        </tbody>
                    </table>
                {% endfor %}

				<div class="pagenation">
					{% for pindex in pagelist %}
                        <a href="/userCenter/userCenterOrder{{ pindex }}/">{{ pindex }}</a>
                    {% endfor %}
				</div>
		</div>
	</div>
{% endblock content%}
</body>
</html>