ttsx/shopping/urls.py
#coding=utf-8
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.index, name='index'),#首页
    url(r'^list/(\w+)/(\w+)/(\d*)$', views.list, name='list'),#列表页
    url(r'^search/(\w+)/(\d+)$', views.search, name='search'),#搜索页
    url(r'^detail/(\w+)/(\d+)$', views.detail, name='detail'),#详情页
    url(r'^addgoods/$', views.addgoods, name='addgoods'),
    url(r'^order/$', views.buy_now, name='order'),#立即购买
    url(r'^notpaid/$', views.notpaid, name='notpaid'),
]

ttsx/ttsx/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('shopping.urls', namespace='shopping')),
    url(r'^userCenter/', include('userCenter.urls', namespace='userCenter')),
    url(r'^favicon.ico$', RedirectView.as_view(url=r'static/favicon.ico')),
]+ static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

ttsx/userCenter/urls.py
#coding=utf-8
from django.conf.urls import url
from userCenter import views
urlpatterns = [
    url(r'^cart/$',views.cart, name='cart'),
    url(r'^cartdel$', views.cartdel, name='cartdel'),
    url(r'^cartchange$', views.cartchange, name='cartchange'),
    url(r'^isselect$', views.isselect, name='isselect'),
    url(r'^allselect$', views.allselect, name='allselect'),
    url(r'^login/$', views.login_register_split, {'get': views.login, 'post': views.toLogin}, name='login'),
    url(r'^logout/$', views.logout_view),
    url(r'^register/$', views.login_register_split, {'get': views.register, 'post': views.createUser}, name='register'),
    url(r'^userCenterInfo/$', views.userCenterInfo),
    url(r'^userCenterSite/$', views.userCenterSite),
    url(r'^userCenterOrder([0-9]*)/$', views.userCenterOrder),
    url(r'^userCenterSite/userAddressUpdate$', views.updatehandler),
]

ttsx/shopping/models.py
#coding=utf-8
from django.db import models

class GoodsInfo(models.Model):
    title = models.CharField(max_length=20,verbose_name='商品信息')    #商品名字
    type = models.CharField(max_length=20,verbose_name='商品类型')     #商品类型
    price = models.DecimalField(max_digits=5,decimal_places=2,verbose_name='商品价格')            #商品价格
    unit = models.CharField(max_length=20,verbose_name='商品单位')     #商品单位
    smallImg = models.ImageField(verbose_name='商品小图')#商品图片
    info = models.CharField(max_length=200,verbose_name='商品简介')   #商品简介
    info_detail = models.TextField(max_length=3000,verbose_name='商品详情') #商品详情
    bigImg = models.ImageField(verbose_name='商品大图')#商品图片
    inventoryNum = models.IntegerField(verbose_name='库存量')
    cliNum = models.IntegerField(verbose_name='点击量')#点击量
    class Meta():
        db_table = 'goods'
        verbose_name = '商品信息'
        verbose_name_plural = verbose_name

    #后台admin站点添加数据显示名字而不是对象
    def __str__(self):
        #__unicode__
        return self.title.encode('utf-8')

ttsx/shopping/views.py
#coding=utf-8
from django.shortcuts import render
from django.http import JsonResponse,HttpResponse
from django.core.paginator import Paginator
from userCenter.models import *
from django.contrib.auth.models import User
import random
from django.contrib.auth.decorators import login_required
import time


# 起始页面，将数据按照type发送到前端
def index(request):
    fruit = GoodsInfo.objects.all().filter(type='新鲜水果')
    seafood = GoodsInfo.objects.all().filter(type='海鲜水产')
    meat = GoodsInfo.objects.all().filter(type='猪牛羊肉')
    egg = GoodsInfo.objects.all().filter(type='禽类蛋品')
    vegetables = GoodsInfo.objects.all().filter(type='新鲜蔬菜')
    ice = GoodsInfo.objects.all().filter(type='速冻食品')
    if request.user.is_authenticated():
        userId = request.user.id
        count = cart.objects.filter(user_id=userId).count()
    else:
        count = 0
    context = {'fruit':fruit[0:4], 'fruit1':fruit[5:8], 'seafood':seafood[0:4], 'seafood1':seafood[5:8], 'meat':meat[0:4], 'meat1':meat[5:8], 'egg':egg[0:4], 'egg1':egg[5:8], 'vegetables':vegetables[0:4], 'vegetables1':vegetables[5:8], 'ice':ice[0:4], 'ice1':ice[0:4], 'count':count}
    return render(request, 'shopping/index.html', context)


def user_count(func):
    def inner(request, *args):
        if request.user.is_authenticated():
            userId = request.user.id
            count = cart.objects.filter(user_id=userId).count()
        else:
            count = 0
        return func(request, count, *args)
    return inner


#列表页面，按照attr进行排序，新品为每种类型商品最后两个，并进行分页
@user_count
def list(request, count, type, attr, pIndex):
    goods = GoodsInfo.objects.all().filter(type=type)
    if attr=='cliNum':
        goods_order = goods.order_by("-"+attr)
    else:
        goods_order = goods.order_by(attr)
    newgoods = [temp for temp in goods]
    p = Paginator(goods_order, 10)
    pIndex = int(pIndex)
    goods_now = p.page(pIndex)
    page_num = p.page_range
    pPrev = pIndex
    pNext = pIndex
    if goods_now.has_previous():
        pPrev = pIndex - 1
    if goods_now.has_next():
        pNext = pIndex + 1
    context = {'goods': goods_now, 'newgoods':newgoods[-2:], 'type':type, 'attr':attr, 'pIndex':pIndex, 'num':page_num, 'pNext':pNext, 'pPrev':pPrev, 'count':count}
    return render(request, 'shopping/list.html', context)


#搜索页面，get方法获取搜索关键字，将搜索到的商品分页显示
@user_count
def search(request, count, attr, pIndex ):
    search_good = request.GET['search_good']
    results = GoodsInfo.objects.filter(info__contains=search_good)
    results_order = results.order_by(attr)
    p = Paginator(results_order, 10)
    pIndex = int(pIndex)
    goods_now = p.page(pIndex)
    page_num = p.page_range
    pPrev = pIndex
    pNext = pIndex
    if goods_now.has_previous():
        pPrev = pIndex - 1
    if goods_now.has_next():
        pNext = pIndex + 1
    goods = GoodsInfo.objects.all()
    newgoods = [temp for temp in goods]
    newlist = []
    for i in range(0,2):
        newlist.append(newgoods[random.randint(0,len(newgoods)-1)])
    context = {'newgoods':newlist, 'results':goods_now, 'attr':attr, 'pIndex':pIndex, 'num':page_num, 'pNext':pNext, 'pPrev':pPrev, 'search_good':search_good, 'count':count}
    return render(request, 'shopping/search.html', context)


# 商品详情页面，展示商品具体信息
@user_count
def detail(request, count, type, goods_id):
    allgoods = GoodsInfo.objects.all().filter(type=type)
    newgoods = [temp for temp in allgoods]
    goods = GoodsInfo.objects.get(id=goods_id)
    #将用户最近浏览的商品加入session
    if request.user.is_authenticated():
        if request.session.get('recent_goods'):
            recent_goods = request.session['recent_goods']
            if len(recent_goods)<5:
                if goods_id not in recent_goods:
                    recent_goods.append(goods_id)
            else:
                recent_goods = recent_goods[-4:]
                if goods_id not in recent_goods:
                    recent_goods.append(goods_id)
            request.session['recent_goods']=recent_goods
        else:
            request.session['recent_goods']=[goods_id,]
    cliNum = goods.cliNum
    goods.cliNum = int(cliNum+1)
    goods.save()
    context = {'type':type, 'goods':goods, 'newgoods':newgoods[-2:], 'count':count}
    return render(request, 'shopping/detail.html', context)

# 当点击购物车图表或者在详情页加入购入车时，将商品及数量信息加入购物车
def addgoods(request):
        user = request.user
        #判断用户是否登录
        if request.user.is_authenticated():
            userId = request.user.id
            goodsid = request.POST.get('goodsid')
            goodsnum = long(request.POST.get('goodsnum'))
            goods_info = GoodsInfo.objects.get(id=goodsid)
            #查询登录用户点击的商品
            cart_good = cart.objects.filter(user_id=userId, goods_info=goodsid)
            #该商品已存在与购物车则数量+1
            if cart_good:
                num = cart_good[0].num
                cart_good[0].num = num + goodsnum
                cart_good[0].save()
            #不存在则增加
            else:
                cart.objects.create(num=goodsnum, user=user, goods_info=goods_info, isselect=1)
            cart_goods = cart.objects.filter(user_id=userId)
            count = cart_goods.count()
        else:
            count = 0
        return JsonResponse({'count': count, 'user':str(user)})


# 定义订单页面商品类
class buy_goods:
    def __init__(self, goods_info, num, subtotal, index=1):
        self.goods_info = goods_info
        self.num = num
        self.subtotal = subtotal
        self.index = index


# 将从详情页面立即购买的商品和购物车里去结算时的商品信息传到订单页面
@login_required
def buy_now(request):
    user = request.user
    userId = request.user.id
    puser = User.objects.get(pk=userId)
    addr = address_info.objects.filter(user=puser.pk)
    if not addr:
        addr = ['']
    #从立即购买处进入订单页面
    if request.GET.get("goodsid",None):
        goodsid = request.GET["goodsid"]
        goodsnum = request.GET["goodsnum"]
        goods_info = GoodsInfo.objects.get(pk=goodsid)
        price = goods_info.price
        subtotal = int(goodsnum)*price
        ordernum = str(int(time.time() * 1000)) + str(int(time.clock() * 1000000))
        order = OrderInfo.objects.create(user=user, state=0 , total=subtotal, ordernum=ordernum)
        OrderDetailInfo.objects.create(order=order, goods=goods_info, goods_price=price, count=1)
        goods = buy_goods(goods_info, goodsnum, subtotal)
        context ={'goods':[goods], 'addr':addr[0],'orderid':order.pk}
    #从购物车进入订单页面
    else:
        goods_order = cart.objects.filter(isselect=1)
        goods = []
        index = 0
        total = 0
        ordernum = str(int(time.time() * 1000)) + str(int(time.clock() * 1000000))
        for goods_cart in goods_order:
            goods_info = goods_cart.goods_info
            goodsnum = goods_cart.num
            price = goods_info.price
            subtotal = int(goodsnum)*price
            total +=subtotal
            goods_cart.delete()
            index += 1
            good = buy_goods(goods_info, goodsnum, subtotal, index)
            goods.append(good)
        order = OrderInfo.objects.create(user=user, state=0, total=total, ordernum=ordernum)
        for goods_cart in goods_order:
            goods_info = goods_cart.goods_info
            goodsnum = goods_cart.num
            price = goods_info.price
            OrderDetailInfo.objects.create(order=order, goods=goods_info, goods_price=price, count=goodsnum)
        context = {'goods':goods,'addr':addr[0], 'orderid':order.pk}
    return render(request,'shopping/place_order.html', context)


#从未完成订单页面到提交订单页面
@login_required()
def notpaid(request):
    userId = request.user.id
    puser = User.objects.get(pk=userId)
    addr = address_info.objects.filter(user=puser.pk)
    if not addr:
        addr = ['']
    ordernum = request.GET.get('ordernum')
    orderinfo = OrderInfo.objects.get(ordernum=ordernum)
    orderdetailinfo = OrderDetailInfo.objects.filter(order_id=orderinfo)
    goods = []
    index = 0
    for detailinfo in orderdetailinfo:
        goodsid = detailinfo.goods_id
        goods_info = GoodsInfo.objects.get(pk=goodsid)
        goodsnum = detailinfo.count
        price = goods_info.price
        subtotal = int(goodsnum)*price
        index += 1
        good = buy_goods(goods_info, goodsnum, subtotal, index)
        goods.append(good)
    context = {'goods':goods, 'addr':addr[0], 'orderid':orderinfo.pk}
    return render(request, 'shopping/place_order.html', context)

ttsx/shopping/templates/shopping/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
天天生鲜-商品详情
{% endblock %}


{% block head %}
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<link rel="stylesheet" type="text/css" href="{%static 'css/reset.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/main.css'%}">
	<script type="text/javascript" src="{%static 'js/jquery-1.12.4.min.js'%}"></script>
    <script type="text/javascript">
        $(function () {
            $(".add").click(function () {
                num = parseInt($(this).siblings(".num_show").val())
                $(this).siblings(".num_show").val(num+1)
                num = parseInt($(this).siblings(".num_show").val())
                price = parseFloat($(".show_pirze em").text())
                $(this).parents(".goods_detail_list").children(".total").children("em").text((num*price).toFixed(2))
            })
            $(".minus").click(function () {
                num = parseInt($(this).siblings(".num_show").val())
                if(num>1){
                    $(this).siblings(".num_show").val(num-1)
                    num = parseInt($(this).siblings(".num_show").val())
                    price = parseFloat($(".show_pirze em").text())
                    $(this).parents(".goods_detail_list").children(".total").children("em").text((num*price).toFixed(2))
                }
            })
            {#当加入购物车时，如果用户未登录则跳到登录页面#}
            $(".add_cart").click(function () {
                goodsid = $(this).parent().siblings("#goodsid").text()
                goodsnum = parseInt($(this).parent().siblings(".goods_num").find(".num_show").val())
                $.post("{% url 'shopping:addgoods' %}",{'goodsid':goodsid, 'goodsnum':goodsnum},function(dic){
                    if(dic.user=='AnonymousUser'){
                        window.location.href = "{% url 'userCenter:login' %}"
                    }
                    else {
                        $("#show_count").text(dic.count)
                    }
				})
            })
            $(".buy_btn").click(function () {
                goodsid = parseInt($(this).parent().siblings("#goodsid").text())
                goodsnum = parseInt($(this).parent().siblings(".goods_num").find(".num_show").val())
                window.location.href = "{% url 'shopping:order' %}?goodsid="+goodsid+"&goodsnum="+goodsnum
            })
        })
    </script>
{% endblock %}


{% block content %}
<div class="search_bar clearfix">
		<a href="{% url 'shopping:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="{% url 'shopping:search' 'id' 1%}" method="get">
			<input type="text" class="input_text fl" name="search_good" id="search_text" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" id="search_button" value="搜索">
            <p><span id='search_result'></span></p>
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'userCenter:cart'%}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{count}}</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="{% url 'shopping:list' '新鲜水果' 'id' 1%}" class="fruit">新鲜水果</a></li>
					<li><a href="{% url 'shopping:list' '海鲜水产' 'id' 1%}" class="seafood">海鲜水产</a></li>
					<li><a href="{% url 'shopping:list' '猪牛羊肉' 'id' 1%}" class="meet">猪牛羊肉</a></li>
					<li><a href="{% url 'shopping:list' '禽类蛋品' 'id' 1%}" class="egg">禽类蛋品</a></li>
					<li><a href="{% url 'shopping:list' '新鲜蔬菜' 'id' 1%}" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="{% url 'shopping:list' '速冻食品' 'id' 1%}" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'shopping:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="{% url 'shopping:index' %}">全部分类</a>
		<span>></span>
		<a href="{% url 'shopping:list' type 'id' 1%}">{{type}}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{goods.bigImg}}"></div>

		<div class="goods_detail_list fr">
			<h3>{{goods.info}}</h3>
			<p>{{goods.info_detail}}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{goods.price}}</em></span>
				<span class="show_unit">单  位：{{goods.unit}}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
			<div class="total">总价：<em>{{goods.price}}元</em></div>
            <p id="goodsid" hidden>{{ goods.id }}</p>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
                <h3>新品推荐</h3>
				<ul>
                    {%for temp in newgoods %}
					<li>
						<a href="{% url 'shopping:detail' type temp.id%}"><img src="{{ temp.smallImg }}"></a>
						<h4><a href="{% url 'shopping:detail' type temp.id%}">{{ temp.info }}</a></h4>
						<div class="prize">￥{{ temp.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{goods.info_detail}}</dd>
				</dl>
			</div>

		</div>
    </div>
{% endblock %}

ttsx/shopping/templates/shopping/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
天天生鲜-商品列表
{% endblock %}


{% block head %}
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<link rel="stylesheet" type="text/css" href="{%static 'css/reset.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/main.css'%}">
    <script type="text/javascript", src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $(".add_goods").click(function () {
                goodsid = $(this).parent().siblings("#goodsid").text()
				goodsnum = 1
                $.post("{% url 'shopping:addgoods' %}",{'goodsid':goodsid, 'goodsnum':goodsnum},function(dic){
                    if(dic.user=='AnonymousUser'){
                        window.location.href = "{% url 'userCenter:login' %}"
                    }
                    else {
                        $(".goods_count").text(dic.count)
                    }
				})
            })
            $("#{{ attr }}").addClass("active")
        })
    </script>
{% endblock %}


{% block content %}
    <div class="search_bar clearfix">
		<a href="{% url 'shopping:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<form action="{% url 'shopping:search' 'id' 1%}" method="get">
			<input type="text" class="input_text fl" name="search_good" id="search_text" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" id="search_button" value="搜索">
            <p><span id='search_result'></span></p>
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'userCenter:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl">{{count}}</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="{% url 'shopping:list' '新鲜水果' 'id' 1%}" class="fruit">新鲜水果</a></li>
					<li><a href="{% url 'shopping:list' '海鲜水产' 'id' 1%}" class="seafood">海鲜水产</a></li>
					<li><a href="{% url 'shopping:list' '猪牛羊肉' 'id' 1%}" class="meet">猪牛羊肉</a></li>
					<li><a href="{% url 'shopping:list' '禽类蛋品' 'id' 1%}" class="egg">禽类蛋品</a></li>
					<li><a href="{% url 'shopping:list' '新鲜蔬菜' 'id' 1%}" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="{% url 'shopping:list' '速冻食品' 'id' 1%}" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'shopping:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="{% url 'shopping:index' %}">全部分类</a>
		<span>></span>
		<a href="#">{{type}}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {%for temp in newgoods %}
					<li>
						<a href="{% url 'shopping:detail' temp.type temp.id%}"><img src="{{ temp.smallImg }}"></a>
						<h4><a href="{% url 'shopping:detail' temp.type temp.id%}">{{ temp.info }}</a></h4>
						<div class="prize">￥{{ temp.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>
		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'shopping:list' type 'id' 1 %}"id="id">默认</a>
				<a href="{% url 'shopping:list' type 'price' 1 %}"id="price">价格</a>
				<a href="{% url 'shopping:list' type 'cliNum' 1 %}"id="cliNum">人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{%for temp in goods%}
				<li>
					<h4><a href="/shopping/detail/{{temp.id}}">{{temp.info}}</a></h4>
                    <p id="goodsid" hidden>{{ temp.id }}</p>
					<a href="{% url 'shopping:detail' temp.type temp.id%}"><img src="{{temp.smallImg}}"></a>
					<h4><a href="{% url 'shopping:detail' temp.type temp.id%}">{{temp.info}}</a></h4>
					<div class="operate">
						<span class="prize">￥{{temp.price}}</span>
						<span class="unit">{{temp.price}}/{{temp.unit}}</span>
						<a href="javascript:;" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{%endfor%}
			</ul>

			<div class="pagenation">
                {% if pPrev == pIndex %}
                    <a href="{% url 'shopping:list' type attr pPrev %}">首页</a>
                    {% else %}
                    <a href="{% url 'shopping:list' type attr pPrev %}">上一页</a>
                {% endif %}
                {% for pindex in num %}
                    {% if pindex == pIndex %}
                    <a href="{% url 'shopping:list' type attr pindex %}" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="{% url 'shopping:list' type attr pindex %}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}
                {% if pNext == pIndex %}
                    <a href="{% url 'shopping:list' type attr pNext %}">末页</a>
                    {% else %}
                    <a href="{% url 'shopping:list' type attr pNext %}">下一页</a>
                {% endif %}

			</div>
		</div>
	</div>
{% endblock %}

ttsx/shopping/templates/shopping/user_center_site.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-用户中心</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="login.html">登录</a>
					<span>|</span>
					<a href="register.html">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/shopping/index/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user_center_info/">· 个人信息</a></li>
				<li><a href="/user_center_order/">· 全部订单</a></li>
				<li><a href="/user_center_site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ addr.address }}（{{ addr.receiver }}收） {{ addr.tel }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="useraddressupdate" method="post">
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="uname">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zipcode">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="tel">
						</div>

						<input type="submit" name='temp' value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>